customCommands:
  containers:
    - name: bash normal
      attach: true
      command: 'docker exec -it {{ .Container.ID }} /bin/bash'
      serviceNames: []
    - name: bash root
      attach: true
      command: 'docker exec -it -u 0 {{ .Container.ID }} /bin/bash'
      serviceNames: []
    - name: own home maxime:maxime
      attach: false
#      command: "docker exec -u 0 {{ .Container.ID }} /bin/bash -c 'find $HOME -type d -print0 | xargs -0 -n1 -P8 chown maxime:maxime'"
      command: "docker exec -u 0 {{ .Container.ID }} /bin/bash -c 'find $HOME -maxdepth 3 -print0 | xargs -0 -n1 -P8 chown maxime:maxime'"
      serviceNames: []


    - name: own home maxime
      attach: false
#      command: "docker exec -u 0 {{ .Container.ID }} /bin/bash -c 'find $HOME -type d -print0 | xargs -0 -n1 -P8 chown maxime:maxime'"
      command: "docker exec -u 0 {{ .Container.ID }} /bin/bash -c 'find $HOME -maxdepth 3 -print0 | xargs -0 -n1 -P8 chown maxime'"
      serviceNames: []


    - name: install chezmoi and start zsh
      attach: true
#      command: "docker exec -u 0 {{ .Container.ID }} /bin/bash -c 'find $HOME -type d -print0 | xargs -0 -n1 -P8 chown maxime:maxime'"
      command: 'docker exec -it {{ .Container.ID }} /bin/bash -c "curl --tlsv1.2 -fsSL https://raw.githubusercontent.com/joihn/dotfiles/master/private_dot_config/executable_auto_deploy.sh | bash && exec \$HOME/.local/bin/zsh"'
      serviceNames: []
    
    - name: zsh normal
      attach: true
      command: 'docker exec -it {{ .Container.ID }} /bin/bash -c "exec \$HOME/.local/bin/zsh"'
      serviceNames: []

    - name: zsh root
      attach: true
      command: 'docker exec -it -u 0 {{ .Container.ID }} /bin/bash -c "exec \$HOME/.local/bin/zsh"'
      serviceNames: []

    - name: copy ID
      attach: false
      command: 'mykittencopy {{ .Container.ID }}'
      serviceNames: []

 
  images:
    - name: bash normal
      attach: true
      command: 'docker run -it {{ .Image.ID }} /bin/bash'
      serviceNames: []
    - name: bash root
      attach: true
      command: 'docker run -it -u 0 {{ .Image.ID }} /bin/bash'
      serviceNames: []
    - name: dive into img 
      attach: true
      command: 'dive {{ .Image.ID }}'
      serviceNames: []
